Test

diff --git a/.github/workflows/Performance_Test_Workflow.yml b/.github/workflows/Performance_Test_Workflow.yml
--- a/.github/workflows/Performance_Test_Workflow.yml
+++ b/.github/workflows/Performance_Test_Workflow.yml
@@ -13,12 +13,6 @@ on:
   workflow_dispatch:
   workflow_call:
 
-  # Triggers the workflow on push or pull request events but only for the "Gab-pipeline-test-branche" branch
-  push:
-    branches: [ "main" ] 
-  pull_request:
-    branches: [ "main" ]
-
 jobs:
   # This workflow contains a single job called "performance-test-build"
   performance-test-build:
@@ -41,8 +35,8 @@ jobs:
     # Makes directories that are needed for logs and reports
     - name: Create Directories for JMeter Logs and Reports
       run: |
-        mkdir -p .github/JMeterTestPlan/Results/Logs
-        mkdir -p .github/JMeterTestPlan/Results/Reports/${{ env.TIMESTAMP }}_Report
+        mkdir -p .github/JMeterPerformanceTest/Results/Logs
+        mkdir -p .github/JMeterPerformanceTest/Results/Reports/${{ env.TIMESTAMP }}_Report
 
     # Update apt-get
     - name: Update apt-get
@@ -98,15 +92,15 @@ jobs:
     # testing
     - name: Run JMeter Test
       run: |
-        jmeter -f -n -t ".github/JMeterTestPlan/Demo web shop Tricentis.jmx" -JjtlFile=.github/JMeterTestPlan/Results/Reports/${{ env.TIMESTAMP }}_Report/${{ env.TIMESTAMP }}_testresults.jtl -Jusername=$JMETER_USERNAME -Jpassword=$JMETER_PASSWORD \
-        -l .github/JMeterTestPlan/Results/Reports/${{ env.TIMESTAMP }}_Report/${{ env.TIMESTAMP }}_testresults.jtl \
-        -e -o .github/JMeterTestPlan/Results/Reports/${{ env.TIMESTAMP }}_Report \
-        -j .github/JMeterTestPlan/Results/Logs/${{ env.TIMESTAMP }}_jmeter.log || (echo "JMeter test failed" && exit 1)
+        jmeter -f -n -t ".github/JMeterPerformanceTest/Demo web shop Tricentis.jmx" -JjtlFile=.github/JMeterPerformanceTest/Results/Reports/${{ env.TIMESTAMP }}_Report/${{ env.TIMESTAMP }}_testresults_performance.jtl -Jusername=$JMETER_USERNAME -Jpassword=$JMETER_PASSWORD \
+        -l .github/JMeterPerformanceTest/Results/Reports/${{ env.TIMESTAMP }}_Report/${{ env.TIMESTAMP }}_testresults_performance.jtl \
+        -e -o .github/JMeterPerformanceTest/Results/Reports/${{ env.TIMESTAMP }}_Report \
+        -j .github/JMeterPerformanceTest/Results/Logs/${{ env.TIMESTAMP }}_jmeter.log || (echo "JMeter test failed" && exit 1)
 
     # Run Groovy Script to Generate Summary Report
     - name: Generate Summary Report
       run: |
-        groovy .github/Scripts/performance-summary-script.groovy
+        groovy .github/Scripts/performance-test-summary-script.groovy
 
     # Check the success or failure status of the test run even when another step might fail after the jmeter test
     - name: Set test result message
@@ -123,7 +117,7 @@ jobs:
     # Compress JMeter Results and Logs
     - name: Compress JMeter Results and Logs
       run: |
-        zip -r jmeter_reports_and_logs_zipped_${{ env.TIMESTAMP }}.zip .github/JMeterTestPlan/Results/Reports/${{ env.TIMESTAMP }}_Report .github/JMeterTestPlan/Results/Logs/${{ env.TIMESTAMP }}_jmeter.log
+        zip -r jmeter_performance_reports_and_logs_zipped_${{ env.TIMESTAMP }}.zip .github/JMeterPerformanceTest/Results/Reports/${{ env.TIMESTAMP }}_Report .github/JMeterPerformanceTest/Results/Logs/${{ env.TIMESTAMP }}_jmeter_performance.log
 
     # Sends email
     - name: Send mail
@@ -187,8 +181,8 @@ jobs:
         convert_markdown: true
         # Optional attachments:
         attachments: |
-          .github/JMeterTestPlan/Results/Logs/${{ env.TIMESTAMP }}_jmeter.log,
-          .github/JMeterTestPlan/Results/Reports/${{ env.TIMESTAMP }}_Report/${{ env.TIMESTAMP }}_summary_report.xml
+          .github/JMeterPerformanceTest/Results/Logs/${{ env.TIMESTAMP }}_jmeter_performance.log,
+          .github/JMeterPerformanceTest/Results/Reports/${{ env.TIMESTAMP }}_Report/${{ env.TIMESTAMP }}_summary_performance_report.xml
         # Optional priority: 'high', 'normal' (default) or 'low'
         priority: low
 
@@ -198,18 +192,18 @@ jobs:
       uses: actions/upload-artifact@v4
       with:
         name: ${{env.TIMESTAMP}}_jmeter-logs
-        path: .github/JMeterTestPlan/Results/Logs/${{ env.TIMESTAMP }}_jmeter.log
+        path: .github/JMeterPerformanceTest/Results/Logs/${{ env.TIMESTAMP }}_jmeter_performance.log
     
     # Upload JMeter logs and report zipped as an artifact
     - name: Upload JMeter zipped Logs and reports
       uses: actions/upload-artifact@v4
       with:
-        name: jmeter_reports_and_logs_zipped_${{ env.TIMESTAMP }}
-        path: jmeter_reports_and_logs_zipped_${{ env.TIMESTAMP }}.zip
+        name: jmeter_performance_reports_and_logs_zipped_${{ env.TIMESTAMP }}
+        path: jmeter_performance_reports_and_logs_zipped_${{ env.TIMESTAMP }}.zip
 
     # Upload report folder as an artifact
     - name: Upload JMeter Test Results
       uses: actions/upload-artifact@v4
       with:
         name: ${{env.TIMESTAMP}}_jmeter-results
-        path: .github/JMeterTestPlan/Results/Reports/${{ env.TIMESTAMP }}_Report
+        path: .github/JMeterPerformanceTest/Results/Reports/${{ env.TIMESTAMP }}_Report
