Test

diff --git a/.github/workflows/Performance_Test_Workflow.yml b/.github/workflows/Performance_Test_Workflow.yml
--- a/.github/workflows/Performance_Test_Workflow.yml
+++ b/.github/workflows/Performance_Test_Workflow.yml
@@ -35,8 +35,8 @@ jobs:
     # Makes directories that are needed for logs and reports
     - name: Create Directories for JMeter Logs and Reports
       run: |
-        mkdir -p The-great-pipeline-of-pipelines/JMeterPerformanceTest/Results/Logs
-        mkdir -p The-great-pipeline-of-pipelines/JMeterPerformanceTest/Results/Reports/${{ env.TIMESTAMP }}_Report
+        mkdir -p JMeterPerformanceTest/Results/Logs
+        mkdir -p JMeterPerformanceTest/Results/Reports/${{ env.TIMESTAMP }}_Report
 
     # Update apt-get
     - name: Update apt-get
@@ -93,15 +93,15 @@ jobs:
     - name: Run JMeter Test
       run: |
         echo "${PWD}"
-        jmeter -f -n -t "The-great-pipeline-of-pipelines/JMeterPerformanceTest/Demo web shop Tricentis.jmx" -JjtlFile=The-great-pipeline-of-pipelines/JMeterPerformanceTest/Results/Reports/${{ env.TIMESTAMP }}_Report/${{ env.TIMESTAMP }}_performance_testresults.jtl -Jusername=$JMETER_USERNAME -Jpassword=$JMETER_PASSWORD \
-        -l The-great-pipeline-of-pipelines/JMeterPerformanceTest/Results/Reports/${{ env.TIMESTAMP }}_Report/${{ env.TIMESTAMP }}_performance_testresults.jtl \
-        -e -o The-great-pipeline-of-pipelines/JMeterPerformanceTest/Results/Reports/${{ env.TIMESTAMP }}_Report \
-        -j The-great-pipeline-of-pipelines/JMeterPerformanceTest/Results/Logs/${{ env.TIMESTAMP }}_jmeter_performance.log || (echo "JMeter test failed" && exit 1)
+        jmeter -f -n -t "JMeterPerformanceTest/Demo web shop Tricentis.jmx" -JjtlFile=JMeterPerformanceTest/Results/Reports/${{ env.TIMESTAMP }}_Report/${{ env.TIMESTAMP }}_performance_testresults.jtl -Jusername=$JMETER_USERNAME -Jpassword=$JMETER_PASSWORD \
+        -l JMeterPerformanceTest/Results/Reports/${{ env.TIMESTAMP }}_Report/${{ env.TIMESTAMP }}_performance_testresults.jtl \
+        -e -o JMeterPerformanceTest/Results/Reports/${{ env.TIMESTAMP }}_Report \
+        -j JMeterPerformanceTest/Results/Logs/${{ env.TIMESTAMP }}_jmeter_performance.log || (echo "JMeter test failed" && exit 1)
 
     # Run Groovy Script to Generate Summary Report
     - name: Generate Summary Report
       run: |
-        groovy The-great-pipeline-of-pipelines/Scripts/performance-test-summary-script.groovy
+        groovy Scripts/performance-test-summary-script.groovy
 
     # Check the success or failure status of the test run even when another step might fail after the jmeter test
     - name: Set test result message
@@ -118,7 +118,7 @@ jobs:
     # Compress JMeter Results and Logs
     - name: Compress JMeter Results and Logs
       run: |
-        zip -r jmeter_performance_reports_and_logs_zipped_${{ env.TIMESTAMP }}.zip The-great-pipeline-of-pipelines/JMeterPerformanceTest/Results/Reports/${{ env.TIMESTAMP }}_Report The-great-pipeline-of-pipelines/JMeterPerformanceTest/Results/Logs/${{ env.TIMESTAMP }}_jmeter_performance.log
+        zip -r jmeter_performance_reports_and_logs_zipped_${{ env.TIMESTAMP }}.zip JMeterPerformanceTest/Results/Reports/${{ env.TIMESTAMP }}_Report JMeterPerformanceTest/Results/Logs/${{ env.TIMESTAMP }}_jmeter_performance.log
 
     # Sends email
     - name: Send mail
@@ -182,8 +182,8 @@ jobs:
         convert_markdown: true
         # Optional attachments:
         attachments: |
-          The-great-pipeline-of-pipelines/JMeterPerformanceTest/Results/Logs/${{ env.TIMESTAMP }}_jmeter_performance.log,
-          The-great-pipeline-of-pipelines/JMeterPerformanceTest/Results/Reports/${{ env.TIMESTAMP }}_Report/${{ env.TIMESTAMP }}_summary_performance_report.xml
+          JMeterPerformanceTest/Results/Logs/${{ env.TIMESTAMP }}_jmeter_performance.log,
+          JMeterPerformanceTest/Results/Reports/${{ env.TIMESTAMP }}_Report/${{ env.TIMESTAMP }}_summary_performance_report.xml
         # Optional priority: 'high', 'normal' (default) or 'low'
         priority: low
 
@@ -193,7 +193,7 @@ jobs:
       uses: actions/upload-artifact@v4
       with:
         name: ${{env.TIMESTAMP}}_jmeter-logs
-        path: The-great-pipeline-of-pipelines/JMeterPerformanceTest/Results/Logs/${{ env.TIMESTAMP }}_jmeter_performance.log
+        path: JMeterPerformanceTest/Results/Logs/${{ env.TIMESTAMP }}_jmeter_performance.log
     
     # Upload JMeter logs and report zipped as an artifact
     - name: Upload JMeter zipped Logs and reports
@@ -207,4 +207,4 @@ jobs:
       uses: actions/upload-artifact@v4
       with:
         name: ${{env.TIMESTAMP}}_jmeter-results
-        path: The-great-pipeline-of-pipelines/JMeterPerformanceTest/Results/Reports/${{ env.TIMESTAMP }}_Report
+        path: JMeterPerformanceTest/Results/Reports/${{ env.TIMESTAMP }}_Report
